Sc docs refactoring
input-output-hk/cardano-documentation pull request #544
Opened 2023-11-02 12:45 UTC by NeilBurgess42

Update links in Cardano documentation that relate to the sidechains open source.

2023-11-06 11:39 UTC, olgahryniuk submitted a review, later dismissed

2023-11-06 19:24 UTC, ShariffL requested changes

2023-11-06 19:24 UTC, ShariffL commented on content/08-cardano-sidechains/03-proof-of-concept-evm-sidechain/04-deploy-smart-contracts/02-setup-development.mdx
> +- Search the transaction hash or contract address on the EVM sidechain [testnet explorer](https://github.com/input-output-hk/blockscout).
@NeilBurgess42 
Replace ''Search the transaction hash or contract address on the EVM sidechain [testnet explorer]'' into
''Search the transaction hash or contract address on a blockexplorer. To setup: https://github.com/input-output-hk/blockscout''

2023-11-08 18:48 UTC, ShariffL approved these changes

2023-11-14 11:47 UTC, olgahryniuk approved these changes

2023-11-14 11:50 UTC, merged